apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbital-inspect.fullname" . }}-frontend
  labels:
    {{- include "orbital-inspect.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "orbital-inspect.frontendSelectorLabels" . | nindent 4 }}
